// Destinations Data
export const destinations = [
  {
    id: 1,
    slug: 'bali-indonesia',
    name: 'Bali, Indonesia',
    region: 'Southeast Asia',
    image: 'https://images.unsplash.com/photo-1537225228614-b8563e69e0e4?w=800&q=80',
    description: 'Tropical paradise with pristine beaches, vibrant culture, and ancient temples',
    shortDescription: 'Island paradise with temples & beaches',
    budget: 'Mid-Range',
    minPrice: 800,
    maxPrice: 2000,
    duration: '7-10 days',
    rating: 4.8,
    reviews: 1250,
    highlights: ['Ubud Terraces', 'Seminyak Beach', 'Bali Temple', 'Rice Paddies'],
    overview: 'Bali is an Indonesian island known for its beaches, rice paddies, and Hindu temples. From the volcanic depths of the island to the stunning beaches, Bali offers something for everyone.',
    bestTime: 'April - October',
    difficulty: 'Easy',
  },
  {
    id: 2,
    slug: 'tokyo-japan',
    name: 'Tokyo, Japan',
    region: 'East Asia',
    image: 'https://images.unsplash.com/photo-1540959375944-7049f642e9d4?w=800&q=80',
    description: 'Vibrant metropolis blending tradition with cutting-edge technology',
    shortDescription: 'Modern city meets ancient tradition',
    budget: 'Luxury',
    minPrice: 2000,
    maxPrice: 5000,
    duration: '5-7 days',
    rating: 4.7,
    reviews: 2100,
    highlights: ['Shibuya Crossing', 'Senso-ji Temple', 'Mount Fuji', 'Akihabara'],
    overview: 'Tokyo is a bustling metropolis that seamlessly blends ancient traditions with futuristic technology. Experience serene temples alongside neon-lit skyscrapers.',
    bestTime: 'March - May, September - November',
    difficulty: 'Medium',
  },
  {
    id: 3,
    slug: 'paris-france',
    name: 'Paris, France',
    region: 'Europe',
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&q=80',
    description: 'The City of Light - iconic romance, art, and exquisite cuisine',
    shortDescription: 'Romantic city of art and culture',
    budget: 'Luxury',
    minPrice: 1500,
    maxPrice: 4000,
    duration: '4-6 days',
    rating: 4.9,
    reviews: 3500,
    highlights: ['Eiffel Tower', 'Louvre Museum', 'Notre-Dame', 'Champs-Élysées'],
    overview: 'Paris is the capital of France and one of the most beautiful cities in the world. Known for iconic landmarks, world-class museums, and romantic ambiance.',
    bestTime: 'April - June, September - October',
    difficulty: 'Easy',
  },
  {
    id: 4,
    slug: 'maldives',
    name: 'Maldives',
    region: 'South Asia',
    image: 'https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?w=800&q=80',
    description: 'Overwater bungalows and crystal-clear turquoise waters',
    shortDescription: 'Luxury island getaway',
    budget: 'Luxury',
    minPrice: 3000,
    maxPrice: 8000,
    duration: '5-7 days',
    rating: 4.9,
    reviews: 890,
    highlights: ['Overwater Bungalows', 'Diving', 'Coral Reefs', 'Water Sports'],
    overview: 'The Maldives is an island nation in the Indian Ocean featuring luxurious resorts, pristine beaches, and world-class diving opportunities.',
    bestTime: 'November - April',
    difficulty: 'Easy',
  },
  {
    id: 5,
    slug: 'new-york-usa',
    name: 'New York, USA',
    region: 'North America',
    image: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800&q=80',
    description: 'The city that never sleeps - iconic skyline and endless entertainment',
    shortDescription: 'The city that never sleeps',
    budget: 'Mid-Range',
    minPrice: 1200,
    maxPrice: 3500,
    duration: '4-5 days',
    rating: 4.6,
    reviews: 2800,
    highlights: ['Statue of Liberty', 'Central Park', 'Times Square', 'Broadway'],
    overview: 'New York City is the largest city in the United States and a global center of art, culture, fashion, and finance. Experience world-famous attractions and diverse neighborhoods.',
    bestTime: 'May - September',
    difficulty: 'Medium',
  },
  {
    id: 6,
    slug: 'dubai-uae',
    name: 'Dubai, UAE',
    region: 'Middle East',
    image: 'https://images.unsplash.com/photo-1512453475868-e1b97e288fb3?w=800&q=80',
    description: 'Luxury shopping, futuristic architecture, and desert adventures',
    shortDescription: 'Ultra-modern desert city',
    budget: 'Luxury',
    minPrice: 1800,
    maxPrice: 4500,
    duration: '4-6 days',
    rating: 4.5,
    reviews: 1600,
    highlights: ['Burj Khalifa', 'Palm Jumeirah', 'Shopping', 'Desert Safari'],
    overview: 'Dubai is a city known for luxury shopping, ultramodern architecture, and a lively nightlife scene. Experience the perfect blend of tradition and innovation.',
    bestTime: 'October - April',
    difficulty: 'Easy',
  },
  {
    id: 7,
    slug: 'barcelona-spain',
    name: 'Barcelona, Spain',
    region: 'Europe',
    image: 'https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800&q=80',
    description: 'Gaudí architecture, beaches, and Mediterranean culture',
    shortDescription: 'Architectural marvel on the coast',
    budget: 'Mid-Range',
    minPrice: 900,
    maxPrice: 2500,
    duration: '4-5 days',
    rating: 4.7,
    reviews: 2200,
    highlights: ['Sagrada Familia', 'Park Güell', 'Gothic Quarter', 'Montjuïc'],
    overview: 'Barcelona is the capital of Catalonia and is famous for its unique architecture, particularly the works of Antoni Gaudí, beautiful beaches, and vibrant culture.',
    bestTime: 'April - May, September - October',
    difficulty: 'Easy',
  },
  {
    id: 8,
    slug: 'singapore',
    name: 'Singapore',
    region: 'Southeast Asia',
    image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80',
    description: 'Modern city-state with fusion cuisine and futuristic attractions',
    shortDescription: 'Garden city of the future',
    budget: 'Mid-Range',
    minPrice: 1000,
    maxPrice: 2800,
    duration: '3-4 days',
    rating: 4.6,
    reviews: 1500,
    highlights: ['Marina Bay Sands', 'Gardens by the Bay', 'Sentosa Island', 'Street Food'],
    overview: 'Singapore is a vibrant city-state that blends modernity with culture. Known for its stunning architecture, excellent food, and efficient transportation.',
    bestTime: 'February - April, July - September',
    difficulty: 'Easy',
  },
];

// Tours Data
export const tours = [
  {
    id: 1,
    slug: 'bali-temple-adventure',
    name: 'Bali Temple Adventure',
    destinationId: 1,
    destinationName: 'Bali, Indonesia',
    price: 1200,
    originalPrice: 1500,
    duration: '7 days',
    image: 'https://images.unsplash.com/photo-1537225228614-b8563e69e0e4?w=800&q=80',
    rating: 4.8,
    reviews: 450,
    description: 'Explore ancient temples, rice paddies, and experience traditional Balinese culture.',
    included: ['Guided tours', 'Accommodation', 'Meals', 'Temple visits'],
    groupSize: '8-12',
    difficulty: 'Easy',
    category: 'Cultural',
    isBestSeller: true,
  },
  {
    id: 2,
    slug: 'tokyo-modern-meets-tradition',
    name: 'Tokyo: Modern Meets Tradition',
    destinationId: 2,
    destinationName: 'Tokyo, Japan',
    price: 2500,
    originalPrice: 3000,
    duration: '6 days',
    image: 'https://images.unsplash.com/photo-1540959375944-7049f642e9d4?w=800&q=80',
    rating: 4.7,
    reviews: 680,
    description: 'Experience the blend of ancient temples and futuristic technology in Tokyo.',
    included: ['JR Pass', 'Accommodation', 'Guided tours', 'Traditional meals'],
    groupSize: '10-15',
    difficulty: 'Medium',
    category: 'Urban',
    isBestSeller: false,
  },
  {
    id: 3,
    slug: 'parisian-romance',
    name: 'Parisian Romance',
    destinationId: 3,
    destinationName: 'Paris, France',
    price: 1800,
    originalPrice: 2200,
    duration: '5 days',
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&q=80',
    rating: 4.9,
    reviews: 920,
    description: 'Fall in love with Paris on this romantic getaway with Louvre and Eiffel Tower.',
    included: ['Accommodation', 'Breakfast', 'Guided tours', 'Seine cruise'],
    groupSize: '6-10',
    difficulty: 'Easy',
    category: 'Romantic',
    isBestSeller: true,
  },
  {
    id: 4,
    slug: 'maldives-luxury-retreat',
    name: 'Maldives Luxury Retreat',
    destinationId: 4,
    destinationName: 'Maldives',
    price: 4500,
    originalPrice: 5500,
    duration: '7 days',
    image: 'https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?w=800&q=80',
    rating: 4.9,
    reviews: 320,
    description: 'Ultimate luxury vacation with overwater bungalows and world-class diving.',
    included: ['5-star resort', 'All meals', 'Diving', 'Water sports', 'Spa'],
    groupSize: '2-4',
    difficulty: 'Easy',
    category: 'Luxury',
    isBestSeller: true,
  },
  {
    id: 5,
    slug: 'nyc-adventure',
    name: 'NYC Adventure',
    destinationId: 5,
    destinationName: 'New York, USA',
    price: 1500,
    originalPrice: 1800,
    duration: '4 days',
    image: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800&q=80',
    rating: 4.6,
    reviews: 780,
    description: 'Discover the best of NYC from Broadway to Central Park.',
    included: ['Accommodation', 'Broadway show', 'City tours', 'Meals'],
    groupSize: '10-20',
    difficulty: 'Medium',
    category: 'Urban',
    isBestSeller: false,
  },
  {
    id: 6,
    slug: 'dubai-desert-luxury',
    name: 'Dubai Desert & Luxury',
    destinationId: 6,
    destinationName: 'Dubai, UAE',
    price: 2200,
    originalPrice: 2700,
    duration: '5 days',
    image: 'https://images.unsplash.com/photo-1512453475868-e1b97e288fb3?w=800&q=80',
    rating: 4.5,
    reviews: 610,
    description: 'Experience luxury shopping and desert safari in Dubai.',
    included: ['Accommodation', 'Desert safari', 'Shopping guide', 'Meals'],
    groupSize: '6-12',
    difficulty: 'Easy',
    category: 'Luxury',
    isBestSeller: false,
  },
  {
    id: 7,
    slug: 'barcelona-gaudi-tour',
    name: 'Barcelona Gaudí Tour',
    destinationId: 7,
    destinationName: 'Barcelona, Spain',
    price: 1100,
    originalPrice: 1400,
    duration: '4 days',
    image: 'https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800&q=80',
    rating: 4.7,
    reviews: 550,
    description: 'Explore Gaudí\'s masterpieces and Mediterranean beaches.',
    included: ['Accommodation', 'Guided tours', 'Museum entries', 'Meals'],
    groupSize: '8-14',
    difficulty: 'Easy',
    category: 'Cultural',
    isBestSeller: false,
  },
  {
    id: 8,
    slug: 'singapore-food-culture',
    name: 'Singapore Food & Culture',
    destinationId: 8,
    destinationName: 'Singapore',
    price: 1300,
    originalPrice: 1600,
    duration: '3 days',
    image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80',
    rating: 4.6,
    reviews: 420,
    description: 'Discover Singapore\'s diverse food culture and modern attractions.',
    included: ['Accommodation', 'Food tours', 'City tours', 'Marina Bay experience'],
    groupSize: '8-12',
    difficulty: 'Easy',
    category: 'Culinary',
    isBestSeller: false,
  },
];

// Activities Data
export const activities = [
  {
    id: 1,
    name: 'Jungle Trekking',
    category: 'Adventure',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    description: 'Explore lush rainforests and discover exotic wildlife.',
    price: 45,
    duration: '4 hours',
    difficulty: 'Medium',
    destinations: ['Bali', 'Barcelona', 'Singapore'],
  },
  {
    id: 2,
    name: 'Scuba Diving',
    category: 'Water Sports',
    image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80',
    description: 'Discover vibrant coral reefs and marine life.',
    price: 120,
    duration: '6 hours',
    difficulty: 'Medium',
    destinations: ['Maldives', 'Bali', 'Singapore'],
  },
  {
    id: 3,
    name: 'Yoga & Meditation',
    category: 'Relaxation',
    image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&q=80',
    description: 'Find peace and balance in serene natural settings.',
    price: 35,
    duration: '2 hours',
    difficulty: 'Easy',
    destinations: ['Bali', 'Maldives', 'Tokyo'],
  },
  {
    id: 4,
    name: 'Hot Air Ballooning',
    category: 'Adventure',
    image: 'https://images.unsplash.com/photo-1486391152825-9e5f8eb4a69e?w=800&q=80',
    description: 'Float above stunning landscapes at sunrise.',
    price: 200,
    duration: '3 hours',
    difficulty: 'Easy',
    destinations: ['Tokyo', 'Paris', 'Dubai'],
  },
  {
    id: 5,
    name: 'Beach Surfing',
    category: 'Water Sports',
    image: 'https://images.unsplash.com/photo-1515238152791-8216ec18a475?w=800&q=80',
    description: 'Ride the waves and master the art of surfing.',
    price: 60,
    duration: '3 hours',
    difficulty: 'Medium',
    destinations: ['Bali', 'Barcelona', 'New York'],
  },
  {
    id: 6,
    name: 'Spa & Wellness',
    category: 'Relaxation',
    image: 'https://images.unsplash.com/photo-1544161515-81e80b8a0e18?w=800&q=80',
    description: 'Pamper yourself with traditional treatments.',
    price: 90,
    duration: '2 hours',
    difficulty: 'Easy',
    destinations: ['Maldives', 'Bali', 'Dubai', 'Singapore'],
  },
  {
    id: 7,
    name: 'City Walking Tour',
    category: 'Cultural',
    image: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800&q=80',
    description: 'Explore historic city streets with local guides.',
    price: 40,
    duration: '3 hours',
    difficulty: 'Easy',
    destinations: ['Paris', 'Tokyo', 'Barcelona', 'New York'],
  },
  {
    id: 8,
    name: 'Mountain Climbing',
    category: 'Adventure',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    description: 'Conquer peaks and enjoy breathtaking views.',
    price: 150,
    duration: '6 hours',
    difficulty: 'Hard',
    destinations: ['Tokyo', 'Paris', 'Barcelona'],
  },
  {
    id: 9,
    name: 'Kayaking',
    category: 'Water Sports',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    description: 'Paddle through scenic waterways and hidden coves.',
    price: 70,
    duration: '4 hours',
    difficulty: 'Easy',
    destinations: ['Maldives', 'Barcelona', 'Singapore', 'Bali'],
  },
  {
    id: 10,
    name: 'Cultural Workshop',
    category: 'Cultural',
    image: 'https://images.unsplash.com/photo-1460661519884-fd02cecee279?w=800&q=80',
    description: 'Learn traditional crafts and customs from locals.',
    price: 55,
    duration: '3 hours',
    difficulty: 'Easy',
    destinations: ['Bali', 'Tokyo', 'Barcelona', 'Paris'],
  },
  {
    id: 11,
    name: 'Desert Safari',
    category: 'Adventure',
    image: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800&q=80',
    description: 'Experience the thrill of desert exploration.',
    price: 110,
    duration: '5 hours',
    difficulty: 'Medium',
    destinations: ['Dubai', 'Paris'],
  },
  {
    id: 12,
    name: 'Fine Dining Experience',
    category: 'Culinary',
    image: 'https://images.unsplash.com/photo-1504674900967-965ba63e3f57?w=800&q=80',
    description: 'Taste exquisite cuisines prepared by renowned chefs.',
    price: 130,
    duration: '3 hours',
    difficulty: 'Easy',
    destinations: ['Paris', 'Tokyo', 'Dubai', 'Singapore'],
  },
];

// Testimonials
export const testimonials = [
  {
    id: 1,
    name: 'Sarah Anderson',
    role: 'Traveler',
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80',
    comment: 'The best travel experience of my life! Every detail was perfectly planned.',
  },
  {
    id: 2,
    name: 'Michael Chen',
    role: 'Adventure Seeker',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80',
    comment: 'Incredible destinations and amazing guides. Highly recommended!',
  },
  {
    id: 3,
    name: 'Emma Wilson',
    role: 'Luxury Traveler',
    image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&q=80',
    comment: 'Premium service with attention to detail. Worth every penny!',
  },
  {
    id: 4,
    name: 'David Martinez',
    role: 'Family Traveler',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80',
    comment: 'Made family vacations so easy and memorable. Thank you!',
  },
];

// Team Data
export const team = [
  {
    id: 1,
    name: 'Alexandra Rose',
    role: 'Founder & CEO',
    image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=300&q=80',
    bio: '15+ years in travel industry, passionate about creating unforgettable journeys.',
  },
  {
    id: 2,
    name: 'James Thompson',
    role: 'Head of Destinations',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&q=80',
    bio: 'Explored 80+ countries, expert in curating premium travel experiences.',
  },
  {
    id: 3,
    name: 'Sofia Rodriguez',
    role: 'Customer Experience Director',
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=300&q=80',
    bio: 'Dedicated to ensuring every traveler has an exceptional experience.',
  },
  {
    id: 4,
    name: 'Marcus Johnson',
    role: 'Adventure Guide Lead',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&q=80',
    bio: 'Certified adventure guide, safety and fun are our top priorities.',
  },
];
